main:
  params: [input]
  steps:
    - init:
        assign:
          - default_companies:
              - name: "TEST-Microsoft"
                url: "https://www.microsoft.com/en-us/corporate-responsibility/esg"
          - company_list: ${default(input.companies, default_companies)}
          - all_results: []
          - final_message: "Workflow started..."

    - iterate_companies:
        for:
          value: company
          in: ${company_list}
          steps:
            - init_loop_vars:
                assign:
                  - scraped_text: null
                  - company_name: null
                  - final_analysis: null
                  - scrape_response: null
                  - analyze_response: null

            - call_scraper:
                try:
                  steps:
                    - http_post_scraper:
                        call: http.post
                        args:
                          url: "https://agent-2-scraper-210318146861.us-central1.run.app"
                          auth:
                            type: OIDC
                          body:
                            name: ${company.name}
                            url: ${company.url}
                        result: scrape_response
                except:
                  as: e
                  steps:
                    - log_scrape_error:
                        call: sys.log
                        args:
                          text: "A scrape error occurred."
                          severity: ERROR

            - process_scrape_result:
                switch:
                  - condition: ${scrape_response != null}
                    steps:
                      - set_scraped_text:
                          assign:
                            - scraped_text: ${default(map.get(scrape_response.body, "scraped_text"), null)}
                            - company_name: ${default(map.get(scrape_response.body, "company_name"), company.name)}

            - check_and_call_analyzer:
                switch:
                  - condition: ${scraped_text != null}
                    steps:
                      - call_analyzer:
                          try:
                            steps:
                              - http_post_analyzer:
                                  call: http.post
                                  args:
                                    url: "https://agent-3-analyzer-210318146861.us-central1.run.app"
                                    auth:
                                      type: OIDC
                                    body:
                                      scraped_text: ${scraped_text}
                                  result: analyze_response
                          except:
                            as: e
                            steps:
                              - log_analyze_error:
                                  call: sys.log
                                  args:
                                    text: "An analysis error occurred."
                                    severity: ERROR

                      - process_analysis_result:
                          switch:
                            - condition: ${analyze_response != null}
                              steps:
                                - set_analysis_result:
                                    assign:
                                      - final_analysis: ${default(map.get(analyze_response.body, "analysis"), null)}

                      - append_result:
                          assign:
                            - current_result:
                                company: ${company_name}
                                source_url: ${company.url}
                                analysis: ${final_analysis}
                            - all_results: ${list.concat(all_results, [current_result])}

    - call_saver:
        try:
          steps:
            - http_post_saver:
                call: http.post
                args:
                  url: "https://agent-4-saver-210318146861.us-central1.run.app"
                  auth:
                    type: OIDC
                  body: ${all_results}
                result: save_response
        except:
          as: e
          steps:
            - log_save_error:
                call: sys.log
                args:
                  text: "Failed to save final results."
                  severity: ERROR
            - set_final_message_on_error:
                assign:
                  - final_message: "Failed to save results."

    - process_save_result:
        switch:
          - condition: ${save_response != null}
            steps:
              - set_final_message:
                  assign:
                    - final_message: ${default(map.get(save_response.body, "message"), "Save status unknown")}

    - final_step:
        return: ${final_message}
