"""
ESW — Contract Generator
Produces a draft Service Agreement (plain-text / Markdown) populated with
calculated fees from PricingCalculator and project metadata.

Output is a ready-to-review document — NOT legal advice.
"""

from __future__ import annotations

from datetime import date, timedelta
from typing import Any

from .pricing_engine import PricingCalculator


_TEMPLATE = """
# SERVICE AGREEMENT

**Between:**

**Ecosystem Services World** ("ESW", "Provider")
ecosystemservices.world

**And:**

**{client_name}** ("Client")
{client_address}

**Effective Date:** {effective_date}

---

## 1. SCOPE OF SERVICES

ESW shall provide the following ecosystem services advisory for the Project
described in Schedule A:

{scope_items}

## 2. PROJECT DESCRIPTION (Schedule A)

| Parameter | Value |
|---|---|
| Project Name | {project_name} |
| Location | {project_location} |
| Estimated CAPEX | USD {project_capex:,.0f} |
| Complexity Score | {complexity_score}/10 |
| Client Type | {client_type} |
| Impact Score | {impact_score}/10 |

## 3. FEES AND PAYMENT

### 3.1 Upfront Advisory Fee

| Item | Amount |
|---|---|
| Upfront Fee | **USD {upfront_fee:,.2f}** |
| Due | Within 30 days of execution |

{upfront_rationale}

### 3.2 Success Fee

| Item | Amount |
|---|---|
| Success Fee Rate | **{success_fee_pct}** of Project deal value at Financial Close |
| Estimated Success Fee | USD {success_fee_estimate:,.2f} |
| Trigger | Financial close of debt/equity/bond issuance for the Project |
| Due | Within 30 days of Financial Close |

{success_rationale}

### 3.3 Subscription Services (Optional)

| Tier | Annual Fee | Includes |
|---|---|---|
| **{subscription_tier}** | USD {subscription_annual:,.0f}/year | {tier_summary} |

Subscription is billed annually in advance. Client may upgrade tier at any
renewal date.

## 4. TERM AND TERMINATION

- **Initial Term**: 12 months from Effective Date.
- **Renewal**: Automatically renews for successive 12-month periods unless
  either party provides 60 days written notice.
- **Termination for Convenience**: Either party may terminate with 60 days
  written notice. Upfront fees are non-refundable. Success fees remain
  payable if Financial Close occurs within 24 months of termination.

## 5. DELIVERABLES

ESW shall deliver the following outputs in bankable, investor-grade format:

{deliverables}

## 6. CONFIDENTIALITY

Both parties agree to maintain confidentiality of all project data,
financial models, and proprietary methodologies shared during the engagement.
This obligation survives termination for a period of 5 years.

## 7. LIMITATION OF LIABILITY

ESW's total liability under this Agreement shall not exceed the total fees
paid by Client. ESW provides advisory services only and does not guarantee
project approval, financing, or regulatory outcomes.

## 8. GOVERNING LAW

This Agreement shall be governed by the laws of {governing_law}.
Disputes shall be resolved by arbitration under ICC rules,
with the seat of arbitration in {arbitration_seat}.

---

## SIGNATURES

**For ESW — Ecosystem Services World**

Name: ____________________________
Title: ____________________________
Date: ____________________________

**For {client_name}**

Name: ____________________________
Title: ____________________________
Date: ____________________________

---

*This document is a draft service agreement generated by ESW's pricing
system. It is not legal advice. Both parties should review with qualified
legal counsel before execution.*

**ESW** | ecosystemservices.world
"""


# ── Scope templates by tier ────────────────────────────────────────────
_SCOPE_BY_TIER = {
    "Essentials": [
        "Regulatory scan for applicable jurisdiction(s)",
        "Baseline ecological desktop assessment",
        "GIS satellite screening and constraint mapping",
    ],
    "Professional": [
        "Regulatory scan — multi-jurisdiction (CSRD/TNFD/ISSB as applicable)",
        "Baseline ecological assessment (desktop + field)",
        "GIS multi-spectral analysis (Sentinel-2, Landsat, TROPOMI)",
        "Nature-based Solutions (NbS) feasibility study",
        "Financial model and bankability memorandum",
        "Carbon/biodiversity credit scoping and methodology selection",
    ],
    "Enterprise": [
        "Full Environmental and Social Impact Assessment (EIA/ESIA)",
        "Regulatory scan — all applicable jurisdictions",
        "GIS multi-criteria suitability analysis (Google Earth Engine)",
        "Nature-based Solutions design to IUCN Global Standard",
        "Blended finance structuring (DFI + bonds + credits)",
        "DFI loan application support (IDB / EBRD / AfDB / ADB)",
        "Green/sustainability bond framework + second-party opinion",
        "Dedicated Project Controller for engagement duration",
        "Annual ecological monitoring and MRV protocol setup",
        "Carbon credit verification cycle support (Verra/Gold Standard)",
    ],
}

_DELIVERABLES_BY_TIER = {
    "Essentials": [
        "Regulatory compliance memo",
        "Ecological baseline report",
        "GIS constraint maps (PDF + GeoTIFF)",
    ],
    "Professional": [
        "Regulatory compliance memo (multi-jurisdiction)",
        "Ecological baseline report with IUCN NbS alignment",
        "GIS analysis package (maps, GeoTIFF, shapefiles)",
        "NbS feasibility study",
        "Financial model (Excel) and bankability memo",
        "Credit scoping report",
    ],
    "Enterprise": [
        "Full EIA/ESIA report (DFI-compliant format)",
        "Regulatory compliance memo (all jurisdictions)",
        "GIS multi-criteria analysis package with Priority Index",
        "NbS detailed design aligned to IUCN Global Standard",
        "Integrated financial model with sensitivity analysis",
        "Bankability memorandum (DFI and bond investor audiences)",
        "Blended finance term sheet",
        "DFI loan application package",
        "Green bond framework document",
        "Annual monitoring protocol and MRV methodology",
    ],
}


class ContractGenerator:
    """Generate a draft Service Agreement from pricing results.

    Parameters
    ----------
    pricing : dict
        Output from PricingCalculator.calculate().
    project_name : str
        Human-readable project name.
    project_location : str
        Project site location.
    client_name : str
        Legal name of the client entity.
    client_address : str
        Client registered address.
    governing_law : str
        Jurisdiction for governing law clause.
    arbitration_seat : str
        City for ICC arbitration seat.
    """

    def __init__(
        self,
        pricing: dict[str, Any],
        project_name: str,
        project_location: str,
        client_name: str,
        client_address: str = "",
        governing_law: str = "England and Wales",
        arbitration_seat: str = "London",
    ) -> None:
        self.pricing = pricing
        self.project_name = project_name
        self.project_location = project_location
        self.client_name = client_name
        self.client_address = client_address or "[Client Address]"
        self.governing_law = governing_law
        self.arbitration_seat = arbitration_seat

    def generate(self) -> str:
        """Return the filled contract as a Markdown string."""
        p = self.pricing
        tier = p["subscription_tier"]

        scope_list = _SCOPE_BY_TIER.get(tier, _SCOPE_BY_TIER["Professional"])
        scope_items = "\n".join(f"- {item}" for item in scope_list)

        deliverable_list = _DELIVERABLES_BY_TIER.get(tier, _DELIVERABLES_BY_TIER["Professional"])
        deliverables = "\n".join(f"- {item}" for item in deliverable_list)

        tier_includes = p.get("tier_includes", [])
        tier_summary = "; ".join(tier_includes[:3])
        if len(tier_includes) > 3:
            tier_summary += f" + {len(tier_includes) - 3} more"

        # Fee rationale text
        impact = p.get("impact_score", 5.0)
        if impact >= 7.0:
            upfront_rationale = (
                "**Note**: Upfront fee reflects a 40% high-impact discount. "
                "ESW's primary compensation is the success fee at Financial Close, "
                "aligning our incentives with your project outcome."
            )
            success_rationale = (
                "**Note**: Success fee applies the high-impact rate. "
                "This structure ensures ESW is invested in your project reaching "
                "Financial Close — we succeed when you succeed."
            )
        elif impact >= 4.0:
            upfront_rationale = (
                "**Note**: Balanced fee structure — upfront covers ESW's advisory "
                "delivery costs. Success fee rewards deal completion."
            )
            success_rationale = (
                "**Note**: Success fee at standard medium-impact rate. "
                "Payable only upon Financial Close."
            )
        else:
            upfront_rationale = (
                "**Note**: Upfront fee covers full advisory delivery cost for "
                "this engagement scope. Reduced success fee reflects early-stage "
                "project status."
            )
            success_rationale = (
                "**Note**: Reduced success fee rate for early-stage projects. "
                "If the project scales and reaches Financial Close, the fee applies "
                "at the contracted rate."
            )

        # Parse success fee pct string to float for template
        success_pct_str = p.get("success_fee", "1.5%")

        return _TEMPLATE.format(
            client_name=self.client_name,
            client_address=self.client_address,
            effective_date=date.today().isoformat(),
            project_name=self.project_name,
            project_location=self.project_location,
            project_capex=p.get("upfront_fee", 0) / 0.001,  # placeholder
            complexity_score=int(impact * 2) if impact <= 5 else min(int(impact + 2), 10),
            client_type="as specified",
            impact_score=impact,
            upfront_fee=p["upfront_fee"],
            success_fee_pct=success_pct_str,
            success_fee_estimate=p["success_fee_estimate_usd"],
            subscription_tier=tier,
            subscription_annual=p["subscription_annual_usd"],
            tier_summary=tier_summary,
            scope_items=scope_items,
            deliverables=deliverables,
            upfront_rationale=upfront_rationale,
            success_rationale=success_rationale,
            governing_law=self.governing_law,
            arbitration_seat=self.arbitration_seat,
        )

    def save(self, path: str) -> str:
        """Write the contract to a file and return the path."""
        content = self.generate()
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path


# ── CLI usage ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    # Example: Culiacán project
    calc = PricingCalculator(
        project_capex=42_500_000,
        complexity_score=8,
        client_type="Government",
    )
    pricing = calc.calculate()

    gen = ContractGenerator(
        pricing=pricing,
        project_name="Green Corridors & Strategic Mobility Hubs — Culiacán",
        project_location="Centro Histórico, Culiacán, Sinaloa, Mexico",
        client_name="Consorcio Mapasin–Parques Alegres",
        client_address="Culiacán, Sinaloa, Mexico",
        governing_law="Mexico (Federal)",
        arbitration_seat="Mexico City",
    )

    print(gen.generate())
